name: pytrain

services:
  pytrain:
    image: pytrain:local
    build:
      context: ../
      dockerfile: PyTrain.Web.Server/Dockerfile
    ports: !reset []
    environment:
      PyTrain_AppOptions__EnablePublicRegistration: "true"
      PyTrain_AppOptions__RequireUserEmailConfirmation: "false"
      PyTrain_AppOptions__DisableEmailSending: "true"
      PyTrain_AppOptions__EnableNetworkTrust: "true"
      PyTrain_AppOptions__AuthenticatorIssuerName: "PyTrain"

  aspire:
    ports: !override
      - "127.0.0.1:18888:18888"
